In [1]:
x=5

In [2]:
import tensorflow as tf


In [3]:
#! pip install langdetect

In [4]:
from preprossecing_script import all_cleaning

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Elaf\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [23]:
#tt=["الناس دي بتنفخ قربة مقدودة بالدارجي كده البلد "]
tt="الناس دي بتنفخ قربة مقدودة بالدارجي كده البلد "
tt=all_cleaning(tt)
print(tt)

الناس دي بتنفخ قربة مقدودة بالدارجي كده البلد 


In [24]:
tt=[tt]
tt

['الناس دي بتنفخ قربة مقدودة بالدارجي كده البلد ']

In [20]:
import pickle

# Load the model from file
with open('../models/tokenizer.pkl', 'rb') as f:
    tokenizer = pickle.load(f)

In [27]:
#text = X_train.values.tolist()
#tt=["الناس دي بتنفخ قربة مقدودة بالدارجي كده البلد "]
##tokenizer.fit_on_texts(text)
tt = tokenizer.texts_to_sequences(tt)


In [28]:
x = pad_sequences(tt, maxlen=100)

In [29]:
x

array([[     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,     13,      9,  60389,  46354,
         47546, 180546,     25,     89]])

In [9]:
from tensorflow.keras.models import load_model

# Load the saved model
loaded_model = load_model(r'../models/my_model.h5')

In [30]:
import numpy as np

# Assuming you have new data in the form of a NumPy array called `new_data`
predictions = loaded_model.predict(x)

1/1 [==============================] - 0s 28ms/step


In [31]:
predictions

array([[0.3829535 , 0.00483712, 0.00377159, 0.00485529, 0.6035825 ]],
      dtype=float32)

In [32]:
predictions.shape

(1, 5)

In [33]:
ss = np.argmax(predictions, axis=1)


In [34]:
ss

array([4], dtype=int64)

In [ ]:
from flask import Flask, request

app = Flask(__name__)

@app.route('/upload', methods=['POST'])
def upload_file():
    if 'file' not in request.files:
        return 'No file part'

    file = request.files['file']

    if file.filename == '':
        return 'No selected file'

    # save the file to disk
    #file.save('/path/to/save/file')
    
    pdfReader = PyPDF2.PdfReader(file)
    def get_text_frompages(pdfReader):
        text = []
        page_number = 0
        
        for page  in pdfReader.pages: 
            text.append(page.extract_text()) #extract text from page
            page_number += 1 #increment page number
            print("page {} extracted".format(page_number))
        return text
    x=get_text_frompages(pdfReader)
    print(x)
    import pandas as pd
    df = pd.DataFrame(columns=['questions','answer one','answer two','answer three','answer four'])
    l=0
    for i in range (len(x)):
     print("new start")
    j=0
    #l=0
    #print(x[i][j],"6")
    while  x[i][j] in [' ','\n']:
        j=j+1
        print("lol")
    while  j < len(x[i])-1 :
        print("staaa")
        print(x[i][j])
        if int(x[i][j])  in list(range(0, 1000)):
        #print(x[i][j])
         con=str(int(x[i][j])+1)
        print(con,"@@@@@")
        l=l+1
        while x[i][j] !=con :
            #l=0
            question=''
            a=""
            b=""
            c=""
            d=""
            while x[i][j] != "?" and j < len(x[i])-1:
             question=question+x[i][j]
            j=j+1
        
            print(question)
            df.loc[l, 'questions']=re.sub(r'\n', '',  question[3:]  )        

            while x[i][j] != "A" and j < len(x[i])-1 :
             j=j+1
            
            while (x[i][j] != "B" and j < len(x[i])-1)  or (x[i][j]=='B' and j < len(x[i])-1 and x[i][j+1]!=' ' ):
             a=a+x[i][j]
             j=j+1
        
            print(a)
            df.loc[l, 'answer one']=re.sub(r'\n', '',  a[4:])             
            while (x[i][j] != "C" and j < len(x[i])-1) or (x[i][j]=='C' and j < len(x[i])-1 and x[i][j+1]!=' '):
             b=b+x[i][j]
             j=j+1
            print(b)
            df.loc[l, 'answer two']=re.sub(r'\n', '',  b[4:])                     
            while x[i][j] != "D" and j < len(x[i])-1 or (x[i][j]=='D' and j < len(x[i])-1 and x[i][j+1]!=' '):
             c=c+x[i][j]
             j=j+1
            print(c)
        
            #print(j)
            #print(len(x[i]))
            df.loc[l, 'answer three']=re.sub(r'\n', '',  c[4:] ) 
            while x[i][j] != "\n" and j < len(x[i])-1 :
                
             d=d+x[i][j]
             j=j+1
            #print(j)
            #print(len(x[i]))
            
            print(d)
            df.loc[l, 'answer four']=re.sub(r'\n', '',d[4:])         
            print('###################')
            print(l,"____")
            print(x[i][j],"^^^^")
            print(con,"___")
            while x[i][j] != con[0] and j < len(x[i])-1 :
                if j < len(x[i]):
                    print("tell")
                    j=j+1
            #print(x[i][j])
            #print("$")
            print("donee")
            break
        #j=j+1
    

    return 'File uploaded successfully'
if __name__ == '__main__':
    app.run()

